pose_controller:
  type: taskspace_controllers/PoseController
  joints:
    - rob1_joint_1
    - rob1_joint_2
    - rob1_joint_3
    - rob1_joint_4
    - rob1_joint_5
    - rob1_joint_6

  base_link: rob1_base_link
  eef_link: rob1_flange

  k_position: 10.0
  k_orient: 10.0

  setpoint_topic: setpoint

as_nullspace_controller:
  type: axially_symmetric_controllers/NullspaceController
  joints:
    - rob1_joint_1
    - rob1_joint_2
    - rob1_joint_3
    - rob1_joint_4
    - rob1_joint_5
    - rob1_joint_6

  base_link: rob1_base_link
  eef_link: rob1_flange

  k_position: 10.0
  k_orient: 10.0

  setpoint_topic: setpoint

  objective_type: maximize_manipulability
  rr_objective:
    k_manip: 10.0

as_twist_decomposition_controller:
  type: axially_symmetric_controllers/TwistDecompositionController
  joints:
    - rob1_joint_1
    - rob1_joint_2
    - rob1_joint_3
    - rob1_joint_4
    - rob1_joint_5
    - rob1_joint_6

  base_link: rob1_base_link
  eef_link: rob1_flange

  k_position: 10.0
  k_orient: 10.0

  setpoint_topic: setpoint

  objective_type: maximize_manipulability
  rr_objective:
    k_manip: 10.0
