task_space_controller:
  type: coordinated_motion_controllers/RobotController
  joints:
    - rob1_joint_1
    - rob1_joint_2
    - rob1_joint_3
    - rob1_joint_4
    - rob1_joint_5
    - rob1_joint_6

  alpha: 0.0
  k_position: 50.0
  k_aiming: 10.0
  k_manip: 1.0
  k_limits: 1.0

  aiming_vec: [0.0, 0.0, 1.0]

  base_link: rob1_base_link
  eef_link: rob1_flange
  setpoint_topic: setpoint
